### ISSUE TITLE
Unable to stop LAN Host server

### ISSUE THREAD

**Issue by Lachee** [SoftwareGuy/Ignorance#12]
When hosting a game using `Ignorance 1.0.9.8-master` and the default Mirror Network Manager (ie just the pong scene with the Ignorance Transport instead), you are unable to stop the server. A InvalidOperationException is thrown. The server starts perfectly fine and people can even connect.
```
InvalidOperationException: Host not created
ENet.Host.CheckCreated () (at Assets/Ignorance/Dependencies/ENet.cs:410)
ENet.Host.Flush () (at Assets/Ignorance/Dependencies/ENet.cs:575)
Mirror.IgnoranceTransport.ClientDisconnect () (at Assets/Ignorance/IgnoranceTransport.cs:509)
Mirror.NetworkConnection.Disconnect () (at Assets/Mirror/Runtime/NetworkConnection.cs:78)
Mirror.NetworkServer.DisconnectAllConnections () (at Assets/Mirror/Runtime/NetworkServer.cs:252)
Mirror.NetworkServer.DisconnectAll () (at Assets/Mirror/Runtime/NetworkServer.cs:234)
Mirror.NetworkServer.Shutdown () (at Assets/Mirror/Runtime/NetworkServer.cs:44)
Mirror.NetworkManager.StopServer () (at Assets/Mirror/Runtime/NetworkManager.cs:321)
Mirror.NetworkManager.StopHost () (at Assets/Mirror/Runtime/NetworkManager.cs:308)
Mirror.NetworkManagerHUD.OnGUI () (at Assets/Mirror/Runtime/NetworkManagerHUD.cs:109)
```

**To Reproduce**
1. Open Pong Example
2. Go to Networkmanager and add Ignorance Transport (removing default Telepathy).
3. Run the game and start a LAN Host
4. Try to stop the server by pressing "stop"

**Specs**
Windows 7 64bit
Unity 2018.1.2 (64bit)
.NET 4.x Equivelent (Mono) [.NET 4.x]
Ignorance 1.0.9.8-master
Latest commit of Mirror

![screenshot of Console](https://s.lu.je/bastion_bhvf8_20190131_1047.png)

**Comment by SoftwareGuy** [comment]
Fixed in commit 7ab032d. Thanks for reporting - oversight on my behalf.
