### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by vis2k** [SoftwareGuy/Ignorance#19]
posting them all in one place for now.

![image](https://user-images.githubusercontent.com/16416509/52852588-5adeb900-3119-11e9-840d-18ce6139c153.png)
weird indentation

---

![image](https://user-images.githubusercontent.com/16416509/52852609-6631e480-3119-11e9-9730-d5531dc2c85f.png)
weird indentation. also the 'costs?' is kinda weird. if you don't exactly know what it does then feel free to leave compression out of it for now. having an uncompressed enet transport is valuable already.

---
![image](https://user-images.githubusercontent.com/16416509/52852665-8792d080-3119-11e9-9d85-05c43ca10eb6.png)
whitespace

---
![image](https://user-images.githubusercontent.com/16416509/52852674-8f527500-3119-11e9-81ec-74309641d698.png)
remove this

---
![image](https://user-images.githubusercontent.com/16416509/52852777-dccee200-3119-11e9-8582-8d3911d5047c.png)
personally I wouldn't worry about buffering until ignorance is 1000% stable. telepathy doesn't buffer (yet) either.

---
![image](https://user-images.githubusercontent.com/16416509/52852844-01c35500-311a-11e9-9589-9b81b802496a.png)
use dictionary.TryGetValue instead of containskey+lookup. faster and shorter.

---
![image](https://user-images.githubusercontent.com/16416509/52852867-156ebb80-311a-11e9-9700-a07c9058357f.png)
use trygetvalue

---
processservermessage:
![image](https://user-images.githubusercontent.com/16416509/52852920-3c2cf200-311a-11e9-869d-0b7ccabba2fa.png)
copy exactly the received packet into a byte[] and then call onserverdatareceived.invoke with the exact packet that was received. don't copy the whole packetdatabuffer in there.
not sure if you have to call incomingevent.packet.dispose either. C# will probably do that for you. unless there is a enet-sharp thing that require you to do that.

---
![image](https://user-images.githubusercontent.com/16416509/52852991-73030800-311a-11e9-88bf-3e8d42d8f36f.png)
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=netframework-4.7.2 just remove, no need to check containskey first.
---
![image](https://user-images.githubusercontent.com/16416509/52853024-8a41f580-311a-11e9-81aa-83c602100455.png)
this allocates a new arraysegment each time someone uses any mirror function with ignorance. probably better to go back to your old serversend without arraysegment. and if you still want arraysegment support then have another serversend function that does that.

---
![image](https://user-images.githubusercontent.com/16416509/52853070-b9f0fd80-311a-11e9-9d89-120a7a55952d.png)
trygetvalue

---
![image](https://user-images.githubusercontent.com/16416509/52853111-d725cc00-311a-11e9-85d0-e93393c6104b.png)
are you sure this works if I am on linux and build for osx? maybe this requires application.platform==osx check? (not 100% sure)

---
![image](https://user-images.githubusercontent.com/16416509/52853202-25d36600-311b-11e9-9f51-e2f93eb347ce.png)
copy directly into a byte[] with exactly the size that you need here too. less magic for now, stability is important, especially if you still have random errors in places.

---
![image](https://user-images.githubusercontent.com/16416509/52853228-397ecc80-311b-11e9-944c-a72941c98e3a.png)
allocates a new arraysegment each time someone calls it from mirror. see above.

---
![image](https://user-images.githubusercontent.com/16416509/52853250-4d2a3300-311b-11e9-94fc-bfbac46bb766.png)
usually better to do this with a git branch instead. but it's fine as long as you remove the old functions later.

---
![image](https://user-images.githubusercontent.com/16416509/52853266-5ddaa900-311b-11e9-88a5-13155f54645f.png)
is this even needed if you only run ignorance from unity?

---
![image](https://user-images.githubusercontent.com/16416509/52853279-6af79800-311b-11e9-81f1-8e7662dbc467.png)
imho a 'bool logDebug' is enough. people should always see warnings and errors.

---
![image](https://user-images.githubusercontent.com/16416509/52853330-937f9200-311b-11e9-94fd-be6340f8a3f8.png)
trygetvalue
---
![image](https://user-images.githubusercontent.com/16416509/52853347-9f6b5400-311b-11e9-8df0-df5d93761758.png)
copy into a byte[] directly like explained above

---
![image](https://user-images.githubusercontent.com/16416509/52853367-aabe7f80-311b-11e9-88f9-5feb51746e42.png)
fix indentation

**Comment by SoftwareGuy** [comment]
This should be addressed in the latest commit(s), could you please check to see if there's any I missed from your list? Thanks.

**Comment by martindevans** [comment]
> this allocates a new arraysegment each time someone uses any mirror function with ignorance. probably better to go back to your old serversend without arraysegment. and if you still want arraysegment support then have another serversend function that does that.

@vis2k This is totally fine - ArraySegment is a struct so constructing it is essentially free. It doesn't cause any garbage to be created which is the only time allocations are a problem.

**Comment by SoftwareGuy** [comment]
I believe this is all resolved now. Going to close, please feel free to re-open if anything burning appears.
