### ISSUE TITLE
Error no GetConectionInfo virtual method in Transport class?

### ISSUE THREAD

**Issue by spookycat** [SoftwareGuy/Ignorance#22]
Just got the latest versions of Mirror and Ignorance but when I bring ignorance in I get the error:
Assets\Mirror\Transports\Ignorance\IgnoranceTransport.cs(225,30): error CS0115: 'IgnoranceTransport.GetConnectionInfo(int, out string)': no suitable method found to override

**Comment by SoftwareGuy** [comment]
What version are you using? v1.0.9.x is legacy but will receive a quality of life update. Ideally you'd have to migrate up to v1.2.0 (master, which is currently 1.2.0-RC3 I believe). So to solve this I'll have to update my Mirror version I'm using for development with Ignorance. This is in the work queue for today.

**Comment by SoftwareGuy** [comment]
Still need to patch the legacy branch.

**Comment by SoftwareGuy** [comment]
Fixed in legacy branch. Closing this for now, please feel free to re-open if it doesn't work as expected
