### ISSUE TITLE
The guid of the metafile is duplicated between Mirror and Ignorance

### ISSUE THREAD

**Issue by shiena** [SoftwareGuy/Ignorance#34]
The following two metafiles have been modified by Unity because the guid is duplicated.

https://github.com/SoftwareGuy/Ignorance/blob/master/Assets/Scenes.meta
https://github.com/vis2k/Mirror/blob/master/Assets/Mirror/Examples/Lobby/Scenes.meta

Perhaps the following tweet may be relevant.
https://twitter.com/mustankatti/status/999652822533591042

**Comment by SoftwareGuy** [comment]
Thanks for pointing that out. I don't know why the Scenes folder got included inside the Unity Package, I think it thought it was a dependency or maybe I clicked a checkbox without double checking. I'll fix that in a commit today.
