### ISSUE TITLE
Feature: LAN Discovery

### ISSUE THREAD

**Issue by SoftwareGuy** [SoftwareGuy/Ignorance#35]
Research and implement a way to do LAN Discovery, so Ignorance can search the local network for any other game servers running using Ignorance.

Implementation to be determined.

**Comment by GabeBigBoxVR** [comment]
We're actually building this internally now, we can share code once we're done.

**Comment by SoftwareGuy** [comment]
That would be excellent if you did. 😄

**Comment by fingerx** [comment]
Any News ?Thanks

**Comment by SoftwareGuy** [comment]
Still WIP.

**Comment by SoftwareGuy** [comment]
Feature request implemented by third party. Current module is on deprecated status.
