### ISSUE TITLE
UnityAsync Error

### ISSUE THREAD

**Issue by Alkanov** [SoftwareGuy/Ignorance#5]
Hi,

I upgraded my project to 2018.2.20f1 then dropped Mirror(2018) and Ignorance (2018 latest release) in the project, I also changed Scripting Runtime Version to .NET 4.x Equivalent.

I am currently stuck with the error below

`Assets/IgnoranceTransport/Dependencies/UnityAsync/TaskYieldInstruction.cs(21,45): error CS1061: Type `Task' does not contain a definition for `IsCompleted' and no extension method `IsCompleted' of type `Task' could be found. Are you missing an assembly reference?`

**Comment by SoftwareGuy** [comment]
Hrm... If I was to take a wild guess I think that UnityAsync was being compiled after Ignorance transport gets compiled.

Can you please right-click `UnityAsync` under `Dependencies` and choose Re-import?

UnityAsync relies on Async threads which is provided by NET 4.x `System.Threading` module, so makes me wonder if the compiler just shat the bed randomly.

**Comment by Alkanov** [comment]
You can close this now

**Comment by SoftwareGuy** [comment]
closed as per request
