### ISSUE TITLE
DLL not found in macOS

### ISSUE THREAD

**Issue by leo150** [SoftwareGuy/Ignorance#52]
I'm experiencing same problem as #3. When I run demo scene and press "LAN Host" I get an error:

> DllNotFoundException: enet
> ENet.Library.Initialize () (at Assets/Mirror/Runtime/Transport/Ignorance/Dependencies/ENet.cs:1059)
> Mirror.IgnoranceClassic.InitializeENET () (at Assets/Mirror/Runtime/Transport/Ignorance/IgnoranceClassic.cs:376)
> Mirror.IgnoranceClassic.ServerStart () (at Assets/Mirror/Runtime/Transport/Ignorance/IgnoranceClassic.cs:262)
> Mirror.NetworkServer.Listen (System.Int32 maxConns) (at Assets/Mirror/Runtime/NetworkServer.cs:136)
> Mirror.NetworkManager.StartServer () (at Assets/Mirror/Runtime/NetworkManager.cs:288)
> Mirror.NetworkManager.StartHost () (at Assets/Mirror/Runtime/NetworkManager.cs:363)
> Mirror.NetworkManagerHUD.OnGUI () (at Assets/Mirror/Runtime/NetworkManagerHUD.cs:55)

Steps to reproduce:
1. Create empty Unity project (Unity 2019.2.2f)
2. Import Mirror asset pack (v3.20.0) 
3. Import Ignorance asset pack (v1.3.3)
4. Run IgnoranceClassic_BasicScene or any other Ignorance demo scene
5. Hit "LAN Host" button

Environment:
macOS 10.14.4
Build target platform is PC, Mac & Linux Standalone

<details>
  <summary>Build Settings</summary>
  
<img width="630" alt="Screen Shot 2019-09-29 at 1 41 01 PM" src="https://user-images.githubusercontent.com/3484524/65839164-c009a800-e2bf-11e9-9d73-32a8e4083cc7.png">

</details>

**Comment by SoftwareGuy** [comment]
Hmm, this is probably due to how I changed the names of the library to better reflect what my build bot spits out. However that said build bot is now misbehaving.

Let me try to replicate this. Will update you ASAP.

**Comment by leo150** [comment]
Great, thank you. I also have to mention that Mirror has introduced some breaking changes in the last version (v4.0.0) that prevent Ignorance from compiling.

**Comment by SoftwareGuy** [comment]
Yep, Mirror 4 caught me offguard. Ignorance 1.3.4 will be coming out hopefully today (I'm just going to fix this and update the transport with no other changes), so I'll make sure I put a reference to this ticket.

**Comment by SoftwareGuy** [comment]
Okay, found the problem. It's an outdated dependency of the ENET wrapper I use (as in, it's not in sync with the one in my ENet-CSharp repository).

I'm just wrapping up 1.3.4 now. I'll make sure I test this on a Mac Editor instance for you.

**Comment by SoftwareGuy** [comment]
Working in Mac Editor.

**Comment by SoftwareGuy** [comment]
Alright, i think i have correctly fixed this in 1.3.4. Could you please check that release and get back to me?

**Comment by leo150** [comment]
It builds, thank you. Tested with Mirror 4.0.7.

**Comment by SoftwareGuy** [comment]
No problems, thanks very much for your report!
