### ISSUE TITLE
Doesn't Work in PlayFab Docker Containers

### ISSUE THREAD

**Issue by TCROC** [SoftwareGuy/Ignorance#53]
Here is the same thing reported as the conversation in Discord:

I am struggling to connect IgnoranceThreaded or IgnoranceClassic while running in the PlayFab MockVM Agent locally on my Windows 10.  It works just fine with Telepathy Transport.

Here is my MultiplayerSettings.json file when trying to connect with Ignorance

```json
{
    "RunContainer": true,
    "OutputFolder": "D:\\PlayFabMultiPlayerLocalAgent\\0.7.1\\Output",
    "NumHeartBeatsForActivateResponse": 10,
    "NumHeartBeatsForTerminateResponse": 6000,
    "TitleId": "",
    "BuildId": "00000000-0000-0000-0000-000000000000",
    "Region": "WestUs",
    "AgentListeningPort": 56001,
    "ServerStartParameters": {
        "ImageDetails": {
            "Registry": "mcr.microsoft.com",
            "ImageName": "playfab/multiplayer",
            "ImageTag": "wsc-10.0.17134.950",
            "Username": "",
            "Password": ""
        },
        "AssetDetails": [
            {
                "MountPath": "C:\\Assets",
                "SasTokens": null,
                "LocalFilePath": "D:\\PlayFabMultiPlayerLocalAgent\\GameServers\\BlockyBall-Mechanics\\BlockyBall-GameServer-0.0.6.zip"
            }
        ],
        "StartGameCommand": "C:\\Assets\\GameServer.exe",
        "PortMappingsList": [
            [
                {
                    "NodePort": 56100,
                    "GamePort": {
                        "Name": "game_port",
                        "Number": 3600,
                        "Protocol": "UDP"
                    }
                }
            ]
        ]
    },
    "SessionConfig": {
        "SessionId": "ba67d671-512a-4e7d-a38c-2329ce181946",
        "SessionCookie": null,
        "InitialPlayers": [ "Player1", "Player2" ]
    }
}
```

And here is the setup in Unity:

![image](https://user-images.githubusercontent.com/24307049/68625368-f6356c80-04a6-11ea-94ee-fcb11f9b3b4d.png)

And this is how I assign the port:

```csharp
public virtual ushort Port
{
    get
    {
        ushort invalidValue = 0;

        switch (transport)
        {
            case IgnoranceClassic ignoranceClassic:
                return (ushort) ignoranceClassic.CommunicationPort;
            case IgnoranceThreaded ignoranceThreaded:
                return (ushort) ignoranceThreaded.CommunicationPort;
            case TelepathyTransport telepathyTransport:
                return telepathyTransport.port;
        }

        Debug.LogError($"There is not a supported transport attached to this {GetType().Name}", this);
        return invalidValue;
    }
    protected set
    {
        switch (transport)
        {
            case IgnoranceClassic ignoranceClassic:
                ignoranceClassic.CommunicationPort = value;
                return;
            case IgnoranceThreaded ignoranceThreaded:
                ignoranceThreaded.CommunicationPort = value;
                return;
            case TelepathyTransport telepathyTransport:
                telepathyTransport.port = value;
                return;
        }

        Debug.LogError($"There is not a supported transport attached to this {GetType().Name}", this);
    }
}
```

I'm at a loss here as to why I can't connect locally in the Docker Container with the Mock VM Agent.  Telepathy works just fine over TCP but Ignorance does not.  I've opened up the ports and communication on my firewall for both TCP and UDP but still no luck.  Even with those ports not opened on my firewall, communication still works just fine locally over TCP so that is not the issue.  Any help would be extremely appreciated.

Here is the docs for the PlayFab Docker Container: https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/servers/locally-debugging-game-servers-and-integration-with-playfab

**Comment by SoftwareGuy** [comment]
Looking into this two-fold:

1) Running it from a docker container itself
2) Running it from inside a PlayFab docker container

Working on the first one first.

**Comment by TCROC** [comment]
Awesome!  Can't wait to get to use Ignorance in PlayFab! :)

**Comment by SoftwareGuy** [comment]
Okay, so apparently starting a server inside a docker container will work fine, but if a client attempts to connect to the docker container's instance it will go boom and emit a huge stack trace. I guess this is what's happening for you but your PlayFab setup isn't logging it.

I'm gonna have to dig deeper. I don't understand why this is happening.

**Comment by SoftwareGuy** [comment]
Okay, looking deeper, I see Windows Server and Windows Client (non-docker, testing it via one instance as server and another as client) builds are working. I wonder if my build bot is making bad builds of the Linux binary blobs.

**Comment by TCROC** [comment]
Okay, that is an interesting find.  I will try creating a build and see if I get similar logs as well.

**Comment by TCROC** [comment]
I checked the logs after running in the Windows10 PlayFab Docker container and everything seems fine:

```
Log: 
Ignorance Server worker thread is ready for connections! I'm listening on UDP port 8080.
Capacity: 4095 peers with 3 channels. My buffer size is 65536 bytes
Stack Trace: 
UnityEngine.Debug:Log(Object)
Mirror.IgnoranceThreaded:ServerWorkerThread(ThreadBootstrapStruct) (at D:/Travis/User Folders/Documents/Unity/Projects/BlockyBallv2/Assets/External/Mirror/Runtime/Transport/Ignorance/IgnoranceThreaded.cs:498)
Mirror.<>c__DisplayClass44_0:<IgnoranceServerThread>b__0() (at D:/Travis/User Folders/Documents/Unity/Projects/BlockyBallv2/Assets/External/Mirror/Runtime/Transport/Ignorance/IgnoranceThreaded.cs:465)
System.Threading.ThreadHelper:ThreadStart()
```

I am unable to connect to it though and no errors were thrown in the file.

This is how it is configured in Unity:

![image](https://user-images.githubusercontent.com/24307049/69292735-d142a700-0bd4-11ea-8ebc-92e51417345c.png)

And this is the json file configured for the MockVMAgent:

```json
{
    "RunContainer": true,
    "OutputFolder": "D:\\PlayFab\\Agent\\0.7.1\\Output",
    "NumHeartBeatsForActivateResponse": 10,
    "NumHeartBeatsForTerminateResponse": 6000,
    "TitleId": "",
    "BuildId": "00000000-0000-0000-0000-000000000000",
    "Region": "WestUs",
    "AgentListeningPort": 56001,
    "ServerStartParameters": {
        "ImageDetails": {
            "Registry": "mcr.microsoft.com",
            "ImageName": "playfab/multiplayer",
            "ImageTag": "wsc-10.0.17134.950",
            "Username": "",
            "Password": ""
        },
        "AssetDetails": [
            {
                "MountPath": "C:\\Assets",
                "SasTokens": null,
                "LocalFilePath": "D:\\PlayFab\\GameServers\\BlockyBall\\BlockyBall-GameServer-0.0.27-Test.zip"
            }
        ],
        "StartGameCommand": "C:\\Assets\\BlockyBallv2.exe",
        "PortMappingsList": [
            [
                {
                    "NodePort": 56100,
                    "GamePort": {
                        "Name": "game_port",
                        "Number": 8080,
                        "Protocol": "UDP"
                    }
                }
            ]
        ]
    },
    "SessionConfig": {
        "SessionId": "ba67d671-512a-4e7d-a38c-2329ce181946",
        "SessionCookie": null,
        "InitialPlayers": [ "Player1", "Player2" ]
    }
}
```

The localhost port on my machine 56100 is mapped to the docker container port 8080.  This works fine with Telepathy, but not Ignorance (In this case Ignorance Threaded).

It works fine when setting ``RunContainer: false`` in the JSON file so its not an issue with the agent.  The behavior seems to suggest that it is to do with the Docker container.

**Comment by TCROC** [comment]
For anyone else that has this issue, IgnoranceThreaded does work in PlayFab Thunderhead in a Linux container.  It does not work with PlayFab's MockVMAgent.  It appears to be an issue with PlayFab's MockVM Agent.

Solution: Upload a build to PlayFab Thunderhead in a Linux Container

Windows Container in Thunderhead have not been tested yet.

**Comment by SoftwareGuy** [comment]
Shit, why did GitHub try to auto-close this?
I'll make note of this in the readme.md file in the next commit.

Thanks again for helping debug this - your assistance was greatly appreciated.

**Comment by TCROC** [comment]
Of course!  Thanks for working with me as well!  Its so nice to find a great tool with a great creator who continuously supports it :)
