### ISSUE TITLE
Calling networkConnection.Disconnect() has no effect

### ISSUE THREAD

**Issue by David548219** [SoftwareGuy/Ignorance#60]
**Describe the bug**
networkConnection.Disconnect() calls have no effect. Using the debugger revealed that connection is still present in NetworkServer.connections after Disconnect is called. I have used basic authentication component to demonstrate it, since this is how I discovered it and it is among the faster ways to set up, but this error is not limited to it. This happens on both client & server. Switching to Telepathy makes everything run smooth. NetworkManager OnServerDisconnect event is also not fired, since no actual disconnect carries out. With enabled debug both on server & client a log message is printed 

> Ignorance: Client disconnection acknowledged

**Repro project**
- Create empty project in Unity.
- Import Mirror.
- Import Ignorance (Last release QualityOfLife-136-20200130).
- Open Ignorance Threaded example scene.
- Add Basic Authenticator component and drag it into Network Manager

**To Reproduce**

1. Build Player for Windows x86_64 with Mono backend
2. Open 2 instances of the player (One in editor to change password from inspector, one in standalone player)
3. Launch Host/Server on one instance
4. Connect to first instance from the second with incorrect credentials.

**Expected behavior**
Client disconnected from server.

**Actual behavior**
Client is stuck in the middle of the connection procedure.

**Desktop**
* OS: Windows 8.1 x64
* Build target: Windows x86_64 Mono
* Unity version: 2019.2.14f1, 2020.1.0b5
* Mirror branch: 11.4.2, 12.11.0

**Comment by SoftwareGuy** [comment]
Another bloody good bug report - nice work!

I've still got the project from #59 in my workbench folder. I'll take a look at this for you using the same repro scene.

**Comment by SoftwareGuy** [comment]
Looking into this now

**Comment by SoftwareGuy** [comment]
Replicated without Network Auth component. Going in hot.

**Comment by SoftwareGuy** [comment]
Okay, I messed up. This will be fixed in Ignorance 1.3.7, which I'm working on getting out the door now. Please test with 1.3.7 and let me know if you still have this problem.

**Comment by David548219** [comment]
I have tested this in 2019.2.14f1. Looks like it works for NetworkConnection only server side, client still has a problem.

Here's my result after Disconnect() is called on the client:
![изображение](https://user-images.githubusercontent.com/34396308/81742417-5df16200-94a0-11ea-939d-e99550c8d7df.png)
NetworkClient.active returns true too.

Server side calls are behaving as expected, connections are disposed and client is disconnected gracefully.

**Comment by SoftwareGuy** [comment]
Hmm, is this still happening in the latest Mirror version? I'll take a look if it is.

**Comment by David548219** [comment]
Still present as of Mirror v16.2.2 and Ignorance 1.3.7 on the client side. Sorry for late response. Looks like this might warrant reopening the issue? @SoftwareGuy

**Comment by SoftwareGuy** [comment]
Are you calling Disconnect on the HostClient connection (connection ID 0)? If you’re in HostClient mode, connection ID 0 is a special connection that is not really connected, but it is there to emulate that it is connected. If you call Disconnect on that, the client will become not ready.

Can you tell me how to reproduce this, like using the Mirror Basic Example?

**Comment by David548219** [comment]
This is related to separate client instances, not host client. Sorry for not including repro steps initially, my bad, here they are:

**To Reproduce**
Steps to reproduce the behavior:
1. Load empty project and import Mirror v16.2.2 and Ignorance 1.3.7.
2. Navigate to Mirror/Examples/Basic/Scenes and open scene Example
3. Change transport from Telepathy to Ignorance Threaded
4. Add BasicAuthenticator component (And drag it to Authenticator property of the manager) and set user and password to some values.
5. Build player (Windows Mono x64).
6. Change username & password values in the inspector (so that they are different from the ones in player).
7. Start a server or host from editor.
8. Try to connect from standalone player to editor.

**Expected behavior**
Client gets disconnected from server because the credentials are wrong.

**Actual behavior**
Client is stuck in the middle of the connection procedure, while on server it gets disconnected.

I use BasicAuthenticator in the example since it uses Disconnect() both server and client side and is the fastest to apply. The issue on client happens because BasicAuthenticator receives the invalid credentials message from server and tries to use Disconnect() to terminate the connection. If Disconnect() is called on server it is fine after the fix you pushed, but calling it on client still has the issue. Switching transport to Telepathy fixes the problem.

**Comment by SoftwareGuy** [comment]
I'm gonna have to refactor the client side of things, which means I might have to fast track Ignorance 1.4 sooner than I thought I would be doing so. At least the client portion of the code. The server side will be a fun challenge.

I tried a few work arounds and somehow got Ignorance to correctly disconnect. However, sometimes it's instantly, sometimes it's like a second after the request, sometimes it doesn't obey and it tries to send data on the connection (which causes ENet to throw a "Cannot send data" message)

**Comment by CorneliusCornbread** [comment]
I think I'm having a similar issue. When calling NetworkManager.singleton.StartHost() and then called NetworkManager.singleton.StopHost() then calling NetworkManager.singleton.StartHost() again, I get an error:

Ignorance encountered a fatal exception. I'm sorry, but I gotta bail - if you believe you found a bug, please report it on the GitHub.
The exception returned was: System.InvalidOperationException: Host creation call failed

I just updated to the latest version, this didn't solve the issue, I get the exact same error.

**Comment by SoftwareGuy** [comment]
How fast are you spamming StartHost and StopHost? Rapidly doing this will be prone to failure.

I can't really give an ETA as per say but I might be able to get a development version of Ignorance 1.4 committed later this week.

**Comment by CorneliusCornbread** [comment]
> How fast are you spamming StartHost and StopHost? Rapidly doing this will be prone to failure.
> 
> I can't really give an ETA as per say but I might be able to get a development version of Ignorance 1.4 committed later this week.

It's done through UI, so probably a second at minimum between start and stop host. I'm using Telepathy in the meantime so it's fine.

**Comment by SoftwareGuy** [comment]
Finally fixed in commit 041bb80 for Ignorance 1.4.0b1.
Going to close this. If it's still not working for you, let me know.
