### ISSUE TITLE
Ignorance not included with Mirror asset

### ISSUE THREAD

**Issue by harleydk** [SoftwareGuy/Ignorance#61]
https://github.com/SoftwareGuy/Ignorance#installation "Download the Unity Package from Releases". It would seem the mirror package no longer contains the Ignorance-transport.

**Comment by SoftwareGuy** [comment]
>https://github.com/SoftwareGuy/Ignorance#installation "Download the Unity Package from Releases". It would seem the mirror package no longer contains the Ignorance-transport. 

@harleydk Ignorance wasn’t bundled at all with the Mirror asset, mainly because due to the reason that I’d have to continuously keep it in sync with Mirror. I might re-word that instruction instructions so it’s clearer.

**Comment by harleydk** [comment]
Yes, I downloaded from here and added to unity without a care. I should have added 'low priority' to this issue, my apologies.
