### ISSUE TITLE
Platform specific Enet / libenet

### ISSUE THREAD

**Issue by gresc574** [SoftwareGuy/Ignorance#66]
changing my platform to Mac while on a windows machine. It's trying to load libenet when it should be loading Enet.

Thanks :)

**Comment by SoftwareGuy** [comment]
Will look into this, might be a Unity thing

**Comment by SoftwareGuy** [comment]
Addressed partially in the Enet-CSharp side of the logic, checking a few things inside Ignorance. WIP.

**Comment by SoftwareGuy** [comment]
Looks like some magic has resolved this.

**Windows Editor**
Set to Windows build, editor library in use: enet
Set to MacOS build, editor library in use: enet
Set to Linux build, editor library in use: enet

**MacOS Editor**
_Windows/Linux modules not installed on the hackintosh being used._
Set to MacOS build, editor library in use: libenet.

**Linux Editor**
To be tested

**Comment by SoftwareGuy** [comment]
Closing as fixed, please report back if it's still a problem.
