### ISSUE TITLE
Client cannot connect

### ISSUE THREAD

**Issue by hesa2020** [SoftwareGuy/Ignorance#68]
Hello i tried switching to Ignorance but it does not connect to the server ( timeout ).

Tried binding server to 127.0.0.1 and local network ip ( 192.168.2.10 )

And tried connecting to: localhost, 127.0.0.1, 192.168.2.10

I also disabled windows firewall just in case.

Nothing is working 👎 

![lXKhBIk 1](https://user-images.githubusercontent.com/2501581/92060947-19e1e000-ed63-11ea-9791-c4abdcea9ea0.png)

**Comment by SoftwareGuy** [comment]
You're using Ignorance Classic which is deprecated. Use Ignorance Threaded instead.
Are you using Windows x86 or Windows x86_64 build target? I see you're running Unity 2019 LTS, good. Firewall is disabled, good.
Also enable "Development Build" in your build settings so you can see any errors going on from the Runtime.

**Comment by hesa2020** [comment]
@SoftwareGuy I had the same issue with Threaded, and i was using x86 i just switched it to x86_64 and turned Dev build on.
Will tell you in a minute how it goes after it compile everything.

**Comment by SoftwareGuy** [comment]
x86 is no longer supported, you will get a "DllNotFound: enet" exception.

If you really need 32bit support for Enet Native then I can build you a 32bit binary. But unless you're releasing a game in a market place like Brazil or Russia where computers are still running 32bit versions of Windows, then target 64Bit.

**Comment by hesa2020** [comment]
@SoftwareGuy Same issue no errors still.
Want to see via discord sharescreen ? 

Hesa#5953

**Comment by SoftwareGuy** [comment]
Does this happen with the included PongChamp demo scene?
I'll test it right now locally.

**Comment by hesa2020** [comment]
Works fine with PongChamp 🤔

**Comment by hesa2020** [comment]
And now it just works fine with my scene 👍

**Comment by SoftwareGuy** [comment]
So it just started working after you loaded PongChamp?

**Comment by hesa2020** [comment]
the editor crashed before i load PongChamp, so i guess a restart fixed it. (Even tho i restarted after switching to x64)
