### ISSUE TITLE
Run-away client receive loops (Not shutting down when required)

### ISSUE THREAD

**Issue by SoftwareGuy** [SoftwareGuy/Ignorance#7]
EDIT: This is only applicable to the mirror2018 branch. master seems to not have this issue.

If one spams the NetworkManagerHUD's "LAN Client" to connect to a Ignorance-powered server, most of the time it will connect and start pumping data correctly. However, if one is fast enough to click "Cancel", then the actual loop that does the data pumping isn't aborted while it is in the Connecting state for some reason (OnClientDisconnect callback doesn't seem to be called). Thus, if you do get a connection, you can end up with 2 connections sending/receiving data on the client instance.

Originally thought to be an ENET problem, it seems that it could be either ENET, something in Mirror (i'm guessing it is likely to be that) or Unity's handing of some functionality. I am not sure. This can be classified as a game-breaking issue if you just have bad luck.

**References**
Issue #39 on ENET-C#, https://github.com/nxrighthere/ENet-CSharp/issues/39

**Comment by nxrighthere** [comment]
If this happens even with .NET 3.5, then no doubt this is a bug in the layer on top of ENet. I never encountered such issues like this in my projects/simulations not in .NET Core nor in Unity.

**Comment by SoftwareGuy** [comment]
The problem is we cannot use NET Framework 3.5 because Mirror for Unity 2018 uses some C# 6.0 language features and the transport layer is asynchronous now rather than calling ClientGetNextPacket(), ServerGetNextPacket(), etc. 

As I mentioned, originally I thought it was an ENET-C# thing, but upon closer inspection it could be either something in ENET-C#, my code, or Mirror. Given how I've made some stupid mistakes in the past, it could simply be that I'm not breaking out of a loop or something when I'm cancelling connections. The problem is that Mirror doesn't seem to fire any callbacks then the user clicks the "Cancel Connection Attempt" button, thus keeping the loop running since no event has been emitted to say "hey, time to wrap up and finish the loop".

I am still isolating the problem to see where the issue is.

**Comment by SoftwareGuy** [comment]
Alright, part of the puzzle solved.

Mirror was not shutting down the client correctly when you click on "Cancel connection attempt" and that has been patched. The issues that still remain are connections not wanting to connect randomly and there seems to be a lockup where it will shall for a few seconds, then resume whatever it was doing (usually it'll connect after that).

**Comment by SoftwareGuy** [comment]
Closing this as it's pretty outdated.
